version: "3.9"

volumes:
  data:
    driver: local

services:
  asgard-data:
    image: ${ASGARD_DOCKER_REGISTER:-docker.io}/navitia/asgard-data-downloader:${MINIO_VERSION}
    environment:
        - MINIO_KEY=${MINIO_KEY}
        - MINIO_SECRET=${MINIO_SECRET}
        - MINIO_HOST=${MINIO_HOST}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - MINIO_COVERAGE=${MINIO_COVERAGE}
        - MINIO_VALHALLA_VERSION=${MINIO_VALHALLA_VERSION}
        
    volumes:
      - data:/data/valhalla
    deploy:
      mode: global
      restart_policy:
        condition: none
            
  asgard-valhalla-service:
    image: ${ASGARD_DOCKER_REGISTER:-docker.io}/navitia/asgard-valhalla-service:${ASGARD_APP_TAG}
    depends_on:
      - "asgard-data"
    volumes:
      - data:/data/valhalla
   
    ports:
      - 8002:8002
      
    deploy:
      mode: global
      restart_policy:
        condition: any

    entrypoint: ["sh", "-c", "wait-for-data.sh && valhalla_service /data/valhalla/valhalla.json 1"]

  asgard:
    image: ${ASGARD_DOCKER_REGISTER:-docker.io}/navitia/asgard-app:${ASGARD_APP_TAG}
    depends_on:
      - "asgard-data"
      - "asgard-valhalla-service"
        
    volumes:
      - data:/data/valhalla
      
    ports:
      - "6000:6000"
      - "8080:8080"
    restart: always

    entrypoint: ["sh", "-c", "wait-for-data.sh && /usr/bin/asgard"]

    environment:
      - ASGARD_SOCKET_PATH=tcp://*:6000
      - ASGARD_WALKING_CACHE_SIZE=50000
      - ASGARD_BIKE_CACHE_SIZE=50000
      - ASGARD_CAR_CACHE_SIZE=50000
      - ASGARD_NB_THREADS=3
      - ASGARD_METRICS_BINDING=0.0.0.0:8080
      - ASGARD_VALHALLA_SERVICE_URL=asgard-valhalla-service:8002
      - ASGARD_VALHALLA_CONF=/data/valhalla/valhalla.json
    deploy:
      mode: global
      restart_policy:
        condition: any
